default:
  tags:
    - docker
  # Image from https://hub.docker.com/_/gcc/ based on Debian
  image: gcc:14

.autotools:
  stage: build
  before_script:
    - apt-get update &&
      apt-get install -y libogg-dev libvorbis-dev
        libsdl1.2-dev libpng-dev libtiff-dev
        doxygen fig2dev texlive texlive-latex-extra
        ${INSTALL_COMPILER} ${INSTALL_EXTRA}
  script:
    - ./autogen.sh
    - ./configure ${CONFIG_FLAGS} || cat config.log
    - make
    - make check
  variables:
    INSTALL_COMPILER: gcc g++

autotools-gcc:
  extends: .autotools
  script:
    - ./autogen.sh
    - ./configure ${CONFIG_FLAGS} || cat config.log
    - make
    - make distcheck
  artifacts:
    paths:
     - libtheora-*.tar.gz
    expire_in: 2 week

autotools-gcc-builddir:
  extends: .autotools
  script:
    - ./autogen.sh
    - mkdir build
    - (cd build && ../configure ${CONFIG_FLAGS}) || cat config.log
    - (cd build && make)
    - (cd build && make check)

autotools-clang:
  extends: .autotools
  script:
    - ./autogen.sh
    - ./configure ${CONFIG_FLAGS} || cat config.log
    - make
    - make distcheck
  variables:
    INSTALL_COMPILER: clang
    CONFIG_FLAGS: CFLAGS=-Wreserved-identifier
    CC: clang

autotools-disable-asm:
  extends: .autotools
  variables:
    CONFIG_FLAGS: --disable-asm

autotools-disable-encoding:
  extends: .autotools
  variables:
    CONFIG_FLAGS: --disable-encode

autotools-enable-telemetry:
  extends: .autotools
  variables:
    CONFIG_FLAGS: --enable-telemetry

autotools-enable-valgrind-testing:
  extends: .autotools
  variables:
    INSTALL_EXTRA: libtool valgrind
    CONFIG_FLAGS: --enable-valgrind-testing

autotools-enable-gcc-sanitizers:
  extends: .autotools
  variables:
    INSTALL_EXTRA: libtool
    CONFIG_FLAGS: --enable-gcc-sanitizers

autotools-mingw:
  extends: .autotools
  script:
    - mkdir build-mingw
    - git clone https://gitlab.xiph.org/xiph/ogg.git build-mingw/ogg-mingw
    - (cd build-mingw/ogg-mingw && ./autogen.sh)
    - (cd build-mingw/ogg-mingw && ./configure ${CONFIG_FLAGS})
    - (cd build-mingw/ogg-mingw && make)
    - ./autogen.sh
    - (cd build-mingw && CPPFLAGS=-I`pwd`/ogg-mingw/include LDFLAGS=-L`pwd`/ogg-mingw/src ../configure --disable-examples ${CONFIG_FLAGS})
    - (cd build-mingw && make)
  variables:
    CONFIG_FLAGS: --disable-shared --host=x86_64-pc-linux-gnu
    INSTALL_COMPILER: gcc-mingw-w64
    CC: x86_64-w64-mingw32-gcc

scons:
  stage: build
  before_script:
    - apt-get update &&
      apt-get install -y libogg-dev libvorbis-dev
        libsdl1.2-dev libpng-dev libtiff-dev
        scons
  script:
    - scons
    - scons -c
